### ISSUE TITLE
Replace `contains` with `in`

### ISSUE THREAD

**Issue by voddan** [Xantier/Kollections#1]
The examples of the `contains` operator are not idiomatic since they use its method form instead of its operator form:

    # Checks and Actions 
    ## Contains

    // Not idiomatic
    intLi­st.c­on­tai­ns(3)  

    // Is idiomatic
    3 in intList 

I think the sheet will greatly benefit from replacing the methods with operators.

**Comment by Xantier** [comment]
Thanks Daniil, 

Good suggestion. Added in checks to HTML.
