### ISSUE TITLE
Add chunked

### ISSUE THREAD

**Issue by alorma** [Xantier/Kollections#4]
```kotlin
fun <T> Iterable<T>.chunked(size: Int): List<List<T>>
```
Splits this collection into a list of lists each not exceeding the given size.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/chunked.html

**Comment by Xantier** [comment]
Thanks alorma,

Could you modify the `docs/index.html` file and add the chunked method description into the grouping section.

**Comment by alorma** [comment]
Should only add on there? or also on txt files, etc... ?

**Comment by Xantier** [comment]
You can also add that to both `txt` && `src`. Most people use the repo via the exposed HTML page so that would be most important.

**Comment by alorma** [comment]
Ok, will do the PR later
